### ISSUE TITLE
Sync with Circuit Python version

### ISSUE THREAD

**Issue by dglaude** [cyborg5/IRLibCP#2]
This library has not moved since 4 months, however, Circuit Python moved from 1.0.0 to 2.0.0 with incompatible *.mpy files.

It would be great to make release/branch (with compatible with Circuit Python version) and not to distribute now incompatible(?) mpy file.

I will give a try of the library with 2.0.0, and try to report here, but I don't know how to generate mpy and some other Circuit Python trick.

**Comment by dglaude** [comment]
I get strange error (not even sending IR), just waiting a few second:

> Adafruit CircuitPython 2.0.0 on 2017-09-12; Adafruit CircuitPlayground Express with samd21g18
> >>> import decode_single
> send a signal
> failed
> Decoded UNKNOWN (0): Value:0x0 Adrs: 0x0 (0 bits)
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "decode_single.py", line 18, in <module>
>   File "/lib/IRLibDecodeBase.py", line 30, in dumpResults
> IndexError: array index out of range

It is however possible to scan one code before the crash.
I gave up my attempt because the remote control I want to learn and replay is not recognized.

**Comment by cyborg5** [comment]
I only recently was aware that the MPY format had changed. I've been tied up with other projects. I will get to it soon.

**Comment by jfrux** [comment]
Anyone have updates on this?  Would love to use this library with CircuitPython 2.x

**Comment by cyborg5** [comment]
Library was just updated for Circuit Python 2.x and tested with 2.2.0 on Express boards. Theoretically should now work with non-express boards but have not tested it.
